name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
          - 'README.md'
          - 'k8s/**'
          - 'ingress-controller/nginx/install-doc.md'
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
  
      - name: Build
        run: go build -o go-web-app
  
      - name: Test
        run: go test ./...

    code-quality:
      runs-on: ubuntu-latest

      steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

    docker-build-and-push:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
    
    update-new-tag-in-helm-chart:
      runs-on: ubuntu-latest

      needs: docker-build-and-push

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm-chart/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "arifdevopstech@hotmail.com"
          git config --global user.name "Arif Sadiq"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push






